---
- name: SETUP SWITCH PORT INTERFACES
  nclu:
     commit: true
     description: "SETUP BOND INTERFACES"
     template: |
          {% for iface in range(1,4) %}
          add int swp{{ iface }}
          {% endfor %}
